force-app/main/default/objects/Packing_checklist__c/Packing_checklist__c.object-meta.xml
<CustomObject>
    <label>Packing checklist</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Packing checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoodsDone__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoodsDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(dangerousGoods20__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dangerousGoods21__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dangerousGoods22__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dangerousGoods23__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>dangerousGoodsDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Merchant&apos;s point of view</description>
    <label>Shipment</label>
    <nameField>
        <label>Container list № (e.g. MBL)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Dangerous_goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tests/TestShipmentTriggerHandler.cls
@isTest
public with sharing class TestShipmentTriggerHandler {

    @isTest
    private static void testAvoidDuplicatesBeforeInsert(){
        String fcId = TestDataFactory.insertFreightContainer();
        Database.SaveResult firstSr = TestDataFactory.insertShipment('test', fcId);
        Test.startTest();
        Database.SaveResult secondSr = TestDataFactory.insertShipment('test', fcId);
        Test.stopTest();
        Assert.areEqual(true, firstSr.isSuccess(), 'First test shipment was not inserted');
        Assert.areEqual(false, secondSr.isSuccess(), 'Duplicate occured');
    }

    @isTest
    private static void testAvoidDuplicatesBeforeUpdate(){
        String fcId = TestDataFactory.insertFreightContainer();
        Database.SaveResult firstSr = TestDataFactory.insertShipment('test1', fcId);
        TestDataFactory.insertShipment('test2', fcId);
        Test.startTest();
        Shipment__c shipmentUpdate = new Shipment__c(
            Id = firstSr.getId(),
            Name = 'test2'
        );
        Database.SaveResult updateResult = Database.update(shipmentUpdate, false);
        Test.stopTest();
        Assert.areEqual(false, updateResult.isSuccess(), 'Unexpected shipment update (duplicate)');
    }

    @isTest
    private static void testHandleNotDangerousGoodsBeforeUpdate(){
        Map<String, String> idMap = TestDataFactory.checklistSetup();
        String sId = idMap.get('sId');
        Test.startTest();
        Shipment__c shipmentUpdate = new Shipment__c(
            Id = sId,
            Dangerous_goods__c = true
        );
        Database.update(shipmentUpdate, false);
        Test.stopTest();
        Packing_checklist__c pc = [SELECT dangerousGoodsDone__c FROM Packing_checklist__c WHERE Shipment__c =:sId];
        Assert.areEqual(false, pc.dangerousGoodsDone__c, 'Dangerous goods stage should not be done');
    }
}