force-app/main/default/objects/Packing_checklist__c/Packing_checklist__c.object-meta.xml
<CustomObject>
    <label>Packing checklist</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Packing checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/fields/Contains_NO__c.field-meta.xml
<CustomField>
    <fullName>Contains_NO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contains NO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods20__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods20__c</fullName>
    <label>dangerousGoods20</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods21__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods21__c</fullName>
    <label>dangerousGoods21</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods22__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods22__c</fullName>
    <label>dangerousGoods22</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods23__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods23__c</fullName>
    <label>dangerousGoods23</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Merchant&apos;s point of view</description>
    <label>Shipment</label>
    <nameField>
        <label>Container list № (e.g. MBL)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Dangerous_goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/ValueSetCTU.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>&apos;&apos;</fullName>
        <default>true</default>
        <label>&apos;&apos;</label>
    </customValue>
    <masterLabel>ValueSetCTU</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PackingChecklistTriggerHandler.cls
public with sharing class PackingChecklistTriggerHandler {

    /**
     * @description checkNo populates the checkbox, which is needed for
     *  navigation through shipments (used in the "Checklist status" formula field)
     * @param  newChecklists 
     */
    public static void checkNo (List<Packing_checklist__c> newChecklists){
        for (Packing_checklist__c checklist : newChecklists) {
            Map<String, Object> fieldsToValue = checklist.getPopulatedFieldsAsMap();
            for (String fieldName : fieldsToValue.keySet()){
                 if(fieldsToValue.get(fieldName) == 'NO'){
                    checklist.Contains_NO__c = true;
                    break;
                 } else {
                    if (checklist.Contains_NO__c == true){
                        checklist.Contains_NO__c = false;
                    }
                 }
            }
        }
    }

    /**
     * @description handleNotDangerousGoods automatically fills
     * dangerous goods checklist items as "not applicable" for
     * safe goods
     * @param  newChecklists newChecklists description
     */
    public static void handleNotDangerousGoods(List<Packing_checklist__c> newChecklists){
        for (Packing_checklist__c checklist : newChecklists) {
            Shipment__c masterShipment = [SELECT Id, Dangerous_goods__c
                                          FROM Shipment__c
                                          WHERE Id = :checklist.Shipment__c];
        if (masterShipment.Dangerous_goods__c){
            checklist.dangerousGoods20__c = 'N/A';
            checklist.dangerousGoods21__c = 'N/A';
            checklist.dangerousGoods22__c = 'N/A';
            checklist.dangerousGoods23__c = 'N/A';
        }
        }
    }


}