force-app/main/default/objects/Packing_checklist__c/Packing_checklist__c.object-meta.xml
<CustomObject>
    <label>Packing checklist</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Packing checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/fields/afterPackingDone__c.field-meta.xml
<CustomField>
    <fullName>afterPackingDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(afterPacking24__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(afterPacking25__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(afterPacking26__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(afterPacking27__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>afterPackingDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/afterPackingNo__c.field-meta.xml
<CustomField>
    <fullName>afterPackingNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(afterPacking24__c, &quot;NO&quot;),
ISPICKVAL(afterPacking25__c, &quot;NO&quot;),
ISPICKVAL(afterPacking26__c, &quot;NO&quot;),
ISPICKVAL(afterPacking27__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>afterPackingNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/closingContainerDone__c.field-meta.xml
<CustomField>
    <fullName>closingContainerDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(closingContainer28__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(closingContainer29__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>closingContainerDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/closingContainerNo__c.field-meta.xml
<CustomField>
    <fullName>closingContainerNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(closingContainer28__c, &quot;NO&quot;),
ISPICKVAL(closingContainer29__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>closingContainerNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/containerConditionDone__c.field-meta.xml
<CustomField>
    <fullName>containerConditionDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(containerCondition8__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(containerCondition9__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(containerCondition10__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(containerCondition11__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(containerCondition12__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>containerConditionDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/containerConditionNo__c.field-meta.xml
<CustomField>
    <fullName>containerConditionNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(containerCondition8__c, &quot;NO&quot;),
ISPICKVAL(containerCondition9__c, &quot;NO&quot;),
ISPICKVAL(containerCondition10__c, &quot;NO&quot;),
ISPICKVAL(containerCondition11__c, &quot;NO&quot;),
ISPICKVAL(containerCondition12__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>containerConditionNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoodsDone__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoodsDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(dangerousGoods20__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dangerousGoods21__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dangerousGoods22__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dangerousGoods23__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>dangerousGoodsDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoodsNo__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoodsNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(dangerousGoods20__c, &quot;NO&quot;),
ISPICKVAL(dangerousGoods21__c, &quot;NO&quot;),
ISPICKVAL(dangerousGoods22__c, &quot;NO&quot;),
ISPICKVAL(dangerousGoods23__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>dangerousGoodsNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dispatchingContainerDone__c.field-meta.xml
<CustomField>
    <fullName>dispatchingContainerDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(dispatchingContainer30__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dispatchingContainer31__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dispatchingContainer32__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dispatchingContainer33__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(dispatchingContainer34__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>dispatchingContainerDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dispatchingContainerNo__c.field-meta.xml
<CustomField>
    <fullName>dispatchingContainerNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(dispatchingContainer30__c, &quot;NO&quot;),
ISPICKVAL(dispatchingContainer31__c, &quot;NO&quot;),
ISPICKVAL(dispatchingContainer32__c, &quot;NO&quot;),
ISPICKVAL(dispatchingContainer33__c, &quot;NO&quot;),
ISPICKVAL(dispatchingContainer34__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>dispatchingContainerNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/packingAreaDone__c.field-meta.xml
<CustomField>
    <fullName>packingAreaDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(packingArea1__c, &quot;&apos;&apos;&quot;)), 
NOT(ISPICKVAL(packingArea2__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingArea3__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingArea4__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingArea5__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingArea6__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingArea7__c, &quot;&apos;&apos;&quot;))), 
true, 
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>packingAreaDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/packingAreaNo__c.field-meta.xml
<CustomField>
    <fullName>packingAreaNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(packingArea1__c, &quot;NO&quot;),
ISPICKVAL(packingArea2__c, &quot;NO&quot;),
ISPICKVAL(packingArea3__c, &quot;NO&quot;),
ISPICKVAL(packingArea4__c, &quot;NO&quot;),
ISPICKVAL(packingArea5__c, &quot;NO&quot;),
ISPICKVAL(packingArea6__c, &quot;NO&quot;),
ISPICKVAL(packingArea7__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>packingAreaNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/packingContainerDone__c.field-meta.xml
<CustomField>
    <fullName>packingContainerDone__c</fullName>
    <formula>IF( AND( NOT(ISPICKVAL(packingContainer13__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingContainer14__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingContainer15__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingContainer16__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingContainer17__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingContainer18__c, &quot;&apos;&apos;&quot;)),
NOT(ISPICKVAL(packingContainer19__c, &quot;&apos;&apos;&quot;))),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>packingContainerDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/packingContainerNo__c.field-meta.xml
<CustomField>
    <fullName>packingContainerNo__c</fullName>
    <formula>IF( OR( ISPICKVAL(packingContainer13__c, &quot;NO&quot;),
ISPICKVAL(packingContainer14__c, &quot;NO&quot;),
ISPICKVAL(packingContainer15__c, &quot;NO&quot;),
ISPICKVAL(packingContainer16__c, &quot;NO&quot;),
ISPICKVAL(packingContainer17__c, &quot;NO&quot;),
ISPICKVAL(packingContainer18__c, &quot;NO&quot;),
ISPICKVAL(packingContainer19__c, &quot;NO&quot;)),
true,
false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>packingContainerNo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Merchant&apos;s point of view</description>
    <label>Shipment</label>
    <nameField>
        <label>Container list № (e.g. MBL)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ChecklistDataWrapper.cls
public with sharing class ChecklistDataWrapper {
    @AuraEnabled
    public String section { get; set; }
    
    @AuraEnabled
    public String icon { get; set; }
    
    @AuraEnabled
    public String label { get; set; }
    
    @AuraEnabled
    public List<CheckListItemsWrapper> items { get; set; }
    
    public ChecklistDataWrapper(String section, String icon, String label, List<CheckListItemsWrapper> itemsList) {
        this.section = section;
        this.icon = icon;
        this.label = label;
        this.items = itemsList;
    }
    
    @AuraEnabled
    public static Response getChecklistData(Id recordId) {
        Response resp;
        try {
            List<ChecklistDataWrapper> data = new List<ChecklistDataWrapper>();
            Packing_checklist__c checklist = [SELECT Shipment__c, packingAreaDone__c, containerConditionDone__c, packingContainerDone__c, 
                                              dangerousGoodsDone__c, afterPackingDone__c, closingContainerDone__c, dispatchingContainerDone__c,
                                              packingAreaNo__c, containerConditionNo__c, packingContainerNo__c, dangerousGoodsNo__c, 
                                              afterPackingNo__c, closingContainerNo__c, dispatchingContainerNo__c 
                                       FROM Packing_checklist__c
                                       WHERE Shipment__c =: recordId
                                       WITH SECURITY_ENFORCED];
            List<CheckListItemsWrapper> items = new List<CheckListItemsWrapper>();
            ChecklistDataWrapper packingArea = new ChecklistDataWrapper(
                'packingArea',
            setIcon(checklist.packingAreaDone__c, checklist.packingAreaNo__c),
            '1. The packing area',
            CheckListItemsWrapper.returnPackingAreaData());
            
            ChecklistDataWrapper containerCondition = new ChecklistDataWrapper(
                'containerCondition',
            setIcon(checklist.containerConditionDone__c, checklist.containerConditionNo__c),
            '2. Container condition',
            CheckListItemsWrapper.returnContainerConditionData());
            
            ChecklistDataWrapper packingContainer = new ChecklistDataWrapper(
                'packingContainer',
            setIcon(checklist.packingContainerDone__c,checklist.packingContainerNo__c),
            '3. Packing the container',
            CheckListItemsWrapper.returnPackingContainerData());
            
            ChecklistDataWrapper dangerousGoods = new ChecklistDataWrapper(
                'dangerousGoods',
            setIcon(checklist.dangerousGoodsDone__c, checklist.dangerousGoodsNo__c),
            '4. Dangerous goods',
            CheckListItemsWrapper.returnDangerousGoodsData());
            
            ChecklistDataWrapper afterPacking = new ChecklistDataWrapper(
                'afterPacking',
            setIcon(checklist.afterPackingDone__c,checklist.afterPackingNo__c),
            '5. Before closing the doors',
            CheckListItemsWrapper.returnAfterPackingData());
            
            ChecklistDataWrapper closingContainer = new ChecklistDataWrapper(
                'closingContainer',
            setIcon(checklist.closingContainerDone__c, checklist.closingContainerNo__c),
            '6. Closing the container',
            CheckListItemsWrapper.returnClosingContainerData());
            
            ChecklistDataWrapper dispatchingContainer = new ChecklistDataWrapper(
                'dispatchingContainer',
            setIcon(checklist.dispatchingContainerDone__c, checklist.dispatchingContainerNo__c),
            '7. Dispatching the container',
            CheckListItemsWrapper.returnDispatchingContainerData());

            data.addAll(new List<ChecklistDataWrapper>{
                packingArea,
                containerCondition,
                packingContainer,
                dangerousGoods,
                afterPacking,
                closingContainer,
                dispatchingContainer
            });

            resp = new Response(data);
        } catch (Exception e) {
            resp = new Response(e);
        }
        return resp;
    }

    public static String setIcon(Boolean stageDone, Boolean stageNo){
        if (stageNo) {
            return 'utility:warning';
        } else if (stageDone) {
            return 'utility:success';
        } else {
            return 'utility:threedots';
        }
    }
}