force-app/main/default/objects/Freight_Container__c/Freight_Container__c.object-meta.xml
<CustomObject>
    <description>Equipment owners point of view.</description>
    <label>Freight Container</label>
    <nameField>
        <label>Freight Container Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Container__c/fields/Current_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Current_Checklist__c</fullName>
    <label>Current Checklist</label>
    <referenceTo>Packing_checklist__c</referenceTo>
    <relationshipLabel>Freight Containers</relationshipLabel>
    <relationshipName>Freight_Containers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/Packing_checklist__c.object-meta.xml
<CustomObject>
    <label>Packing checklist</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Packing checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/fields/Freight_Container__c.field-meta.xml
<CustomField>
    <fullName>Freight_Container__c</fullName>
    <label>Freight Container</label>
    <referenceTo>Freight_Container__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FreightContainerController.cls
public with sharing class FreightContainerController {

    /**
     * @description It's a service method for click handler on every reference item
     * @param  title - value of a button data-id attribute (title / fileName)
     * @return        id of the proper .pdf file
     */ 
    @AuraEnabled(cacheable=true)
    public static String getFileRecordId(String title){      
        try {
            return [SELECT ContentDocumentId 
                    FROM ContentVersion
                    WHERE Title = :title AND Description = 'CTU Reference' 
                    LIMIT 1].ContentDocumentId;      
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }
    /**
     * @description It provides checklist id for further use
     * @param  recordId id of current freight container
     * @return          id of current checklist
     */
    @AuraEnabled(cacheable=true)
    public static String getCurrentChecklistId(String recordId){
        try {
            return [SELECT Current_Checklist__c 
                    FROM Freight_Container__c 
                    WHERE Id = :recordId].Current_Checklist__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
     * @description It updates values of checklists
     * @param  currentChecklistId id of the proper object
     * @param  valueId            full name of the field to be updated
     * @param  value              'YES', 'NO' or 'N/A' string
     */
    @AuraEnabled
    public static void updateRadioValue(String currentChecklistId, String valueId, String value){
        try {
        //List<Packing_checklist__c> pc = [SELECT :valueId FROM ];
        //pc.id = currentChecklistId;
        //pc.valueId = value;
        //update pc;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}