force-app/main/default/objects/Freight_Container__c/Freight_Container__c.object-meta.xml
<CustomObject>
    <description>Equipment owners point of view.</description>
    <label>Freight Container</label>
    <nameField>
        <label>Freight Container Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/Packing_checklist__c.object-meta.xml
<CustomObject>
    <label>Packing checklist</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Packing checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/fields/Freight_Container__c.field-meta.xml
<CustomField>
    <fullName>Freight_Container__c</fullName>
    <label>Freight Container</label>
    <referenceTo>Freight_Container__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/ShipmentId__c.field-meta.xml
<CustomField>
    <fullName>ShipmentId__c</fullName>
    <description>This field shall be filled from Apex. This Id and Freight Container Id together serve as a key for the particular checklist. It may contain several shipment Ids in the case of an LCL shipment.</description>
    <label>ShipmentId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Merchant&apos;s point of view</description>
    <label>Shipment</label>
    <nameField>
        <label>Container list № (e.g. MBL)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/FCL_LCL__c.field-meta.xml
<CustomField>
    <fullName>FCL_LCL__c</fullName>
    <label>FCL/LCL</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FCL</fullName>
            </value>
            <value>
                <fullName>LCL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Freight_Container__c.field-meta.xml
<CustomField>
    <fullName>Freight_Container__c</fullName>
    <label>Freight Container</label>
    <referenceTo>Freight_Container__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {

    public static String insertContentVersion(){
        String txt = '/test.txt';
        ContentVersion cv = new ContentVersion(
                ContentLocation = 'S',
                PathOnClient = txt,
                Title = txt,
                Description = 'CTU Reference',
                VersionData = Blob.valueOf(txt));
        Database.SaveResult sr = Database.insert(cv, false);
        String cvId = sr.getId();
        return cvId;
    }

    public static Map<String, String> checklistSetup(){
        Freight_Container__c fc = new Freight_Container__c(Name = 'test');
        Database.SaveResult srFc = Database.insert(fc, false);
        String fcId = srFc.getId();

        Shipment__c s = new Shipment__c(Name = 'test', FCL_LCL__c = 'FCL', Freight_Container__c = fcId);
        Database.SaveResult srS = Database.insert(s, false);
        String sId = srS.getId();

        Packing_checklist__c pc = new Packing_checklist__c(Freight_Container__c = fcId, ShipmentId__c = sId);
        Database.SaveResult srPc = Database.insert(pc, false);
        String pcId = srPc.getId();

        Map<String, String> idMap = new Map<String, String>();
        idMap.put('fcId', fcId);
        idMap.put('sId', sId);
        idMap.put('pcId', pcId);
        
        return idMap;
    }

}