force-app/main/default/objects/Freight_Container__c/Freight_Container__c.object-meta.xml
<CustomObject>
    <description>Equipment owners point of view.</description>
    <label>Freight Container</label>
    <nameField>
        <label>Freight Container Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/Packing_checklist__c.object-meta.xml
<CustomObject>
    <label>Packing checklist</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Packing checklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packing checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods20__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods20__c</fullName>
    <label>dangerousGoods20</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods21__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods21__c</fullName>
    <label>dangerousGoods21</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods22__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods22__c</fullName>
    <label>dangerousGoods22</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/dangerousGoods23__c.field-meta.xml
<CustomField>
    <fullName>dangerousGoods23__c</fullName>
    <label>dangerousGoods23</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ValueSetCTU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/Freight_Container__c.field-meta.xml
<CustomField>
    <fullName>Freight_Container__c</fullName>
    <label>Freight Container</label>
    <referenceTo>Freight_Container__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Packing_checklist__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packing checklists</relationshipLabel>
    <relationshipName>Packing_checklists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Merchant&apos;s point of view</description>
    <label>Shipment</label>
    <nameField>
        <label>Container list № (e.g. MBL)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist</label>
    <referenceTo>Packing_checklist__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Dangerous_goods__c.field-meta.xml
<CustomField>
    <fullName>Dangerous_goods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dangerous goods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Freight_Container__c.field-meta.xml
<CustomField>
    <fullName>Freight_Container__c</fullName>
    <label>Freight Container</label>
    <referenceTo>Freight_Container__c</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/ValueSetCTU.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>YES</fullName>
    </customValue>
    <customValue>
        <fullName>NO</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>&apos;&apos;</fullName>
        <default>true</default>
        <label>&apos;&apos;</label>
    </customValue>
    <masterLabel>ValueSetCTU</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ShipmentTriggerHandler.cls
/**
 * @description Following methods encapsulate a whole ShipmentTrigger logic
 * @author Mykola Kanunnikov (Nick Eve)
 */ 
public with sharing class ShipmentTriggerHandler {

    //Shipment__c.Name means Master Bill of Lading (MBL) № or equivalent

    private static final String DUPLICATE_ERROR = 'No duplicates for already existing shipment-container pairs allowed';

    /**
     * @description It ensures that shipment-container pairs are unique.
     * @param  newShipments 
     */
    public static void avoidDuplicatesBeforeInsert(List<Shipment__c> newShipments){
        List<String> shipmentNames = new List<String>();
        List<String> shipmentContainers = new List<String>();
        for (Shipment__c shipment : newShipments) {
            shipmentNames.add(shipment.Name);
            shipmentContainers.add(shipment.Freight_Container__c);
        }
        List<Shipment__c> existingShipments = [SELECT Id
                                               FROM Shipment__c
                                               WHERE Name IN: shipmentNames
                                               AND Freight_Container__c IN: shipmentContainers
                                               WITH SECURITY_ENFORCED];
        if (!existingShipments.isEmpty()) {
            newShipments[0].addError(DUPLICATE_ERROR);
        }
    }

    /**
     * @description It ensures that shipment-container pairs are unique.
     * @param  newShipments
     * @param  oldShipments
     */
    public static void avoidDuplicatesBeforeUpdate(List<Shipment__c> newShipments, List<Shipment__c> oldShipments){
        List<String> newShipmentNames = new List<String>();
        List<String> newShipmentContainers = new List<String>();
        List<String> oldShipmentNames = new List<String>();
        List<String> oldShipmentContainers = new List<String>();
        for(Integer i = 0; i < newShipments.size(); i++){
            newShipmentNames.add(newShipments[i].Name);
            newShipmentContainers.add(newShipments[i].Freight_Container__c);
            oldShipmentNames.add(oldShipments[i].Name);
            oldShipmentContainers.add(oldShipments[i].Freight_Container__c);
        }
        if (!newShipmentNames.equals(oldShipmentNames) || !newShipmentContainers.equals(oldShipmentContainers)){ 
            List<Shipment__c> linkedShipments = [SELECT Id
                                                 FROM Shipment__c
                                                 WHERE Name IN: newShipmentNames
                                                 AND Freight_Container__c IN: newShipmentContainers
                                                 WITH SECURITY_ENFORCED];
            if (!linkedShipments.isEmpty()){
                newShipments[0].addError(DUPLICATE_ERROR);
            } 
        }
    }
    
    /**
     * @description createChecklist creates a Packing_checklist__c, which
     * we need as storage for values and relationships.
     * If goods are safety, corresponding checklist items shall be prepopulated
     * @param  newShipments list of new Shipmnent__c 
     */
    public static void createChecklist(List<Shipment__c> newShipments){
        List<Packing_checklist__c> pcList = new List<Packing_checklist__c>();
        String dangerousGoodsValue = 'N/A';
        for (Shipment__c shipment : newShipments) {
            if(shipment.Dangerous_goods__c){
                dangerousGoodsValue = '\'\'';
            }
            Packing_checklist__c pc = new Packing_checklist__c(
                Freight_Container__c = shipment.Freight_Container__c,
                Shipment__c = shipment.id,
                dangerousGoods20__c = dangerousGoodsValue,
                dangerousGoods21__c = dangerousGoodsValue,
                dangerousGoods22__c = dangerousGoodsValue,
                dangerousGoods23__c = dangerousGoodsValue
            );
            pcList.add(pc);
        }
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, pcList);
        Database.SaveResult[] checklistSaveResult = Database.insert(decision.getRecords(), false);
        updateChecklistLink(checklistSaveResult, newShipments);
    }

    /**
     * @description handleNotDangerousGoodsBeforeUpdate fills
     * dangerous goods checklist items as "not applicable" for
     * safe goods and depopulates them for dangerous
     * @param  newShipments 
     * @param  oldShipments 
     */ 
    public static void handleNotDangerousGoodsBeforeUpdate(List<Shipment__c> newShipments, List<Shipment__c> oldShipments){
        List<Packing_checklist__c> pcForUpdate = new List<Packing_checklist__c>();
        List<Shipment__c> changedDangerousShipments = new List<Shipment__c>();
        for (Integer i = 0; i < newShipments.size(); i++){
            if(newShipments[i].Dangerous_goods__c != oldShipments[i].Dangerous_goods__c){
                changedDangerousShipments.add(newShipments[i]);
            }
        }
        List<Packing_checklist__c> detailChecklists = [SELECT Id, dangerousGoods20__c, dangerousGoods21__c, 
                                                       dangerousGoods22__c, dangerousGoods23__c
                                                       FROM Packing_checklist__c
                                                       WHERE Shipment__c IN: changedDangerousShipments
                                                       WITH SECURITY_ENFORCED];   
        String dangerousGoodsValue = 'N/A';
        for (Integer i = 0; i < detailChecklists.size(); i++) {
            if(changedDangerousShipments[i].Dangerous_goods__c){
                dangerousGoodsValue = '\'\'';
            }
            detailChecklists[i].dangerousGoods20__c = dangerousGoodsValue;
            detailChecklists[i].dangerousGoods21__c = dangerousGoodsValue;
            detailChecklists[i].dangerousGoods22__c = dangerousGoodsValue;
            detailChecklists[i].dangerousGoods23__c = dangerousGoodsValue;
            pcForUpdate.add(detailChecklists[i]);
        }  
        SObjectAccessDecision decision = Security.stripInaccessible(AccessType.UPDATABLE, pcForUpdate);
        Database.update(decision.getRecords(), false);
    }


    /**
     * @description It populates shipment-checklist lookup field
     * @param  checklistSaveResult 
     * @param  newShipments        
     */
    private static void updateChecklistLink (Database.SaveResult[] checklistSaveResult, List<Shipment__c> newShipments){
        List<Shipment__c> linkedShipments = new List<Shipment__c>();
            for (Integer i = 0; i < newShipments.size(); i++) {
                ctuapptest__Shipment__c linkedShipment = new ctuapptest__Shipment__c(
                    Id = newShipments[i].id,
                    Checklist__c = checklistSaveResult[i].getId());
                linkedShipments.add(linkedShipment);
            }
            SObjectAccessDecision decision = Security.stripInaccessible(AccessType.UPDATABLE, linkedShipments);
            Database.update(decision.getRecords(), false);
    }


}